obj-$(CONFIG_CAMERA_FLASH_SM5714_OBJ) += is-flash-sm5714.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor
