obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += is-device-module-base.o

#obj-$(CONFIG_CAMERA_CIS_2P6_OBJ) += is-device-module-2p6.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor
