obj-$(CONFIG_CAMERA_ACT_SELECT) += is-helper-actuator-i2c.o
obj-$(CONFIG_CAMERA_ACT_FP5529_OBJ) += is-actuator-fp5529.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/module_framework
