obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += is-cis.o
obj-$(CONFIG_CAMERA_CIS_SR846_OBJ) += is-cis-sr846.o
obj-$(CONFIG_CAMERA_CIS_GC5035_OBJ) += is-cis-gc5035.o
obj-$(CONFIG_CAMERA_CIS_GM2_OBJ) += is-cis-gm2.o
obj-$(CONFIG_CAMERA_CIS_GC02M1_OBJ) += is-cis-gc02m1.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/
